sudo: required
language: go
go:
  - "1.9.x"
services:
  - docker

addons:
  apt:
    packages:
      - rpm

notifications:
  email: false

env:
  global:
    - SKEEMA_TEST_IMAGES="mysql:5.6,mysql:5.7"

install: true

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -v -service=travis-ci
  - go vet ./...
  - test -z "$(gofmt -s -d {.,fs,workspace,util}/*.go 2>&1)"
  - go list -f '{{.Dir}}' ./... | xargs golint -set_exit_status

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
